.PHONY: clean All

All:
	@echo "----------Building project:[ connectfour - Debug ]----------"
	@cd "connectfour" && "$(MAKE)" -f  "connectfour.mk"
clean:
	@echo "----------Cleaning project:[ connectfour - Debug ]----------"
	@cd "connectfour" && "$(MAKE)" -f  "connectfour.mk" clean
